// Top 30 Forex Pairs
// symbol: used for storage & lookup | name: displayed as ratio | base/quote: for live rate computation
export const FOREX_TICKERS: { symbol: string; name: string; price: number; category: string; base: string; quote: string }[] = [
    { symbol: "EURUSD", name: "EUR/USD", price: 0, category: "FOREX", base: "EUR", quote: "USD" },
    { symbol: "USDJPY", name: "USD/JPY", price: 0, category: "FOREX", base: "USD", quote: "JPY" },
    { symbol: "GBPUSD", name: "GBP/USD", price: 0, category: "FOREX", base: "GBP", quote: "USD" },
    { symbol: "USDCHF", name: "USD/CHF", price: 0, category: "FOREX", base: "USD", quote: "CHF" },
    { symbol: "AUDUSD", name: "AUD/USD", price: 0, category: "FOREX", base: "AUD", quote: "USD" },
    { symbol: "USDCAD", name: "USD/CAD", price: 0, category: "FOREX", base: "USD", quote: "CAD" },
    { symbol: "NZDUSD", name: "NZD/USD", price: 0, category: "FOREX", base: "NZD", quote: "USD" },
    { symbol: "EURGBP", name: "EUR/GBP", price: 0, category: "FOREX", base: "EUR", quote: "GBP" },
    { symbol: "EURJPY", name: "EUR/JPY", price: 0, category: "FOREX", base: "EUR", quote: "JPY" },
    { symbol: "EURCHF", name: "EUR/CHF", price: 0, category: "FOREX", base: "EUR", quote: "CHF" },
    { symbol: "EURAUD", name: "EUR/AUD", price: 0, category: "FOREX", base: "EUR", quote: "AUD" },
    { symbol: "EURCAD", name: "EUR/CAD", price: 0, category: "FOREX", base: "EUR", quote: "CAD" },
    { symbol: "EURNZD", name: "EUR/NZD", price: 0, category: "FOREX", base: "EUR", quote: "NZD" },
    { symbol: "GBPJPY", name: "GBP/JPY", price: 0, category: "FOREX", base: "GBP", quote: "JPY" },
    { symbol: "GBPCHF", name: "GBP/CHF", price: 0, category: "FOREX", base: "GBP", quote: "CHF" },
    { symbol: "GBPAUD", name: "GBP/AUD", price: 0, category: "FOREX", base: "GBP", quote: "AUD" },
    { symbol: "GBPCAD", name: "GBP/CAD", price: 0, category: "FOREX", base: "GBP", quote: "CAD" },
    { symbol: "GBPNZD", name: "GBP/NZD", price: 0, category: "FOREX", base: "GBP", quote: "NZD" },
    { symbol: "AUDJPY", name: "AUD/JPY", price: 0, category: "FOREX", base: "AUD", quote: "JPY" },
    { symbol: "AUDCAD", name: "AUD/CAD", price: 0, category: "FOREX", base: "AUD", quote: "CAD" },
    { symbol: "AUDCHF", name: "AUD/CHF", price: 0, category: "FOREX", base: "AUD", quote: "CHF" },
    { symbol: "AUDNZD", name: "AUD/NZD", price: 0, category: "FOREX", base: "AUD", quote: "NZD" },
    { symbol: "CADJPY", name: "CAD/JPY", price: 0, category: "FOREX", base: "CAD", quote: "JPY" },
    { symbol: "CADCHF", name: "CAD/CHF", price: 0, category: "FOREX", base: "CAD", quote: "CHF" },
    { symbol: "CHFJPY", name: "CHF/JPY", price: 0, category: "FOREX", base: "CHF", quote: "JPY" },
    { symbol: "NZDJPY", name: "NZD/JPY", price: 0, category: "FOREX", base: "NZD", quote: "JPY" },
    { symbol: "NZDCAD", name: "NZD/CAD", price: 0, category: "FOREX", base: "NZD", quote: "CAD" },
    { symbol: "NZDCHF", name: "NZD/CHF", price: 0, category: "FOREX", base: "NZD", quote: "CHF" },
    { symbol: "USDMXN", name: "USD/MXN", price: 0, category: "FOREX", base: "USD", quote: "MXN" },
    { symbol: "USDZAR", name: "USD/ZAR", price: 0, category: "FOREX", base: "USD", quote: "ZAR" },
];
